### ISSUE TITLE
Add to Chrome Web Store

### ISSUE THREAD

**Issue by yeldarby** [IceCreamYou/Chrome-BigConsole#1]
Curious why the installation needs to be cloned from github; would be much easier to install on other machines without having to have an entire dev environment.

Could you add to the Chrome Web Store?

**Comment by IceCreamYou** [comment]
The reason I haven't added it to the Chrome Web Store is because I think it's not ready for general usage until the cyclic return value problem is fixed. Once it is, I'll submit it to the store.

I haven't had much reason to work on this project lately, but I'd happily accept pull requests :smiley:

**Comment by IceCreamYou** [comment]
Added! https://chrome.google.com/webstore/detail/bigconsole/klommbdmeefgobphaflhmnieheipjajm

:smile:
