### ISSUE TITLE
Add an option to enable autocompletion

### ISSUE THREAD

**Issue by IceCreamYou** [IceCreamYou/Chrome-BigConsole#10]
Instructions here: https://github.com/ajaxorg/ace/wiki/How-to-enable-Autocomplete-in-the-Ace-editor

Example: https://github.com/ajaxorg/ace/blob/master/demo/autocompletion.html

It's possible some fiddling from those pages are needed.

The code should be changed in [setupEditor()](https://github.com/IceCreamYou/Chrome-BigConsole/blob/master/panel.js#L293) in panel.js.

While we're at it, might as well consider adding options around indentation (spaces/tabs, 2 or 4), line wrap, font, theme, and keyboard handling (e.g. vim-style).

**Comment by t0lkman** [comment]
:+1:

**Comment by IceCreamYou** [comment]
There has also been a request for changing the color/theme of the code editor, which also makes sense to implement at the same time.

**Comment by IceCreamYou** [comment]
This is resolved by #18 (mostly - that PR didn't address the indentation, line wrap, font, and keyboard handling issues, but we can look at that if it's requested separately; autocompletion and theme changes were the most frequent requests).
