### ISSUE TITLE
Is is possible to put the code on the left?

### ISSUE THREAD

**Issue by DinisCruz** [IceCreamYou/Chrome-BigConsole#11]
and the return value on the right?

I kind prefer to code that way

(and btw, pretty nice extension)

**Comment by IceCreamYou** [comment]
Hmm, that is not currently possible, but all that is required is to switch the #log and #console-wrapper divs in panel.html. Would need to be behind a setting though. Contributions are welcome :)

Glad you're enjoying the extension.

**Comment by DinisCruz** [comment]
where can I do that? (can it be done without redeploying the extension?)

**Comment by IceCreamYou** [comment]
Well you can do it locally if you want, either by following the [instructions](https://github.com/IceCreamYou/Chrome-BigConsole#installation) to run the extension in Developer Mode or by finding the location that the extension is installed to from the Chrome Web Store. Just be aware that if you take the second approach, your change will get overridden if you upgrade the extension.

**Comment by IceCreamYou** [comment]
Resolved by #18!
