### ISSUE TITLE
support async functions

### ISSUE THREAD

**Issue by UziTech** [IceCreamYou/Chrome-BigConsole#16]
```javascript
async function t(){};
```

will show an error `Missing ";" before statement`

**Comment by IceCreamYou** [comment]
Honestly, I'm not sure why that's happening, and it seems kind of hard to find answers to that online. It doesn't happen in the "kitchen sink" example on the Ace Editor website, but maybe they're using a newer version of the JavaScript linter.

**Comment by UziTech** [comment]
looks like this issue is related: https://github.com/ajaxorg/ace/issues/3160

**Comment by UziTech** [comment]
could you update ace. this might be fixed.

**Comment by IceCreamYou** [comment]
I would accept a PR 🙂 I am not using this extension myself any more, having gotten used to just hitting Shfit+Enter in the Console or using the Sources tab, with all the advantages those options bring. As a result it is hard to prioritize maintaining this extension.
