### ISSUE TITLE
Yes, yes, resizable panes

### ISSUE THREAD

**Issue by donShakespeare** [IceCreamYou/Chrome-BigConsole#2]
Very awesome extension, weldone!

**Comment by Chris2011** [comment]
Yeah please add this feature :)

**Comment by EranSch** [comment]
I just proposed #4 to add support for resizable panes. Woohoo!

![resize](https://cloud.githubusercontent.com/assets/1479206/10820938/231312f4-7e26-11e5-8488-321153e7e35e.gif)

**Comment by IceCreamYou** [comment]
Version 1.2 has this feature thanks to Swingline0 and it is publishing on the Chrome Store right now :smiley:
