### ISSUE TITLE
can you support shortcut?

### ISSUE THREAD

**Issue by ghost** [IceCreamYou/Chrome-BigConsole#21]
i Love Shortcut.

**Comment by IceCreamYou** [comment]
What do you want shortcuts to do? There are some [keyboard shortcuts](https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts) that are already present, if that's what you're asking for, plus Ctrl+Enter to run the code

**Comment by IceCreamYou** [comment]
No response for 25 days, so I'm closing this.
