### ISSUE TITLE
Please add an option to override the console with big console

### ISSUE THREAD

**Issue by Chris2011** [IceCreamYou/Chrome-BigConsole#3]
What I use is under network or elements, I press esc and the console comes up. This is not possible with big console. It would be nice to have an option where you can override the normal console

**Comment by IceCreamYou** [comment]
I would like this too, but unfortunately it is not possible. Chrome Dev Tools just doesn't provide the APIs to do it :disappointed:

**Comment by Chris2011** [comment]
Ok maybe not override but is there an API to to the same as for the console? Not for ESC but maybe for CTRL + Whatever to split the view and show the BigConsole Vertically OR Horizontally? (With an option)

**Comment by IceCreamYou** [comment]
No :disappointed: Chrome doesn't provide APIs to create new sidebars / panels / whatever other than a new panel in the dev tools (which is how BigConsole already works) and it also doesn't allow modifying existing panels.

**Comment by Chris2011** [comment]
Ok, thx for the feedback.
