### ISSUE TITLE
clearing the output

### ISSUE THREAD

**Issue by curioussavage** [IceCreamYou/Chrome-BigConsole#6]
After using the extension for a moment I feel like it would be more useful to have the clear button clear the output pane on the left. IMO its really easy to cmd + a and then delete whats in the editor

**Comment by IceCreamYou** [comment]
Just committed a [change](https://github.com/IceCreamYou/Chrome-BigConsole/commit/54d211b3d0ad0210ba9239dc7ee80c17cffd4a54) that makes BigConsole support the `clear()` function. So now if you run `clear()` from the BigConsole, it will clear the output pane.

**Comment by freewind** [comment]
Is it better to provide a "clear" button on the output panel, so I can click on it? Type the `clear()` in the code is too verbose

**Comment by IceCreamYou** [comment]
Well, I'm not sure where it would make sense to put that button. No other consoles I'm aware of have buttons to clear the output, they just all take the `clear()` approach. I'm not saying that's the best way to do it, just that nobody else seems to have figured out a better way either. If someone comes up with an unobtrusive way to do this, I'd accept a PR though.
